################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: REPLACEME
  productionDescription: REPLACEME
  whoIsItFor: REPLACEME
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: REPLACEME™
featuredFeatures:
  - title: REPLACE ME
    description:  REPLACE ME
    tags: ["REPLACEME", "REPLACEME", "REPLACEME"]
    bullets: ["REPLACEME", "REPLACEME" ]  
    relatedDocs:
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME1.md
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME2.md
      - relatedDoc: 
        title: REPLACEME
        description: REPLACEME
        link: ./docs/REPLACE-ME3.md
    relatedAPIs:
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "patch"        
        path: "/v1/REPLACEME1"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "post"        
        path: "/v1/REPLACEME2"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "get"        
        path: "/v1/REPLACEME3"
