################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: AcceptanceSolutionsAPAC
  productionDescription: REPLACEME
  whoIsItFor: REPLACEME
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: AcceptanceSolutionsAPAC™
featuredFeatures:
  - title: Credit Issuance
    description:  AcceptanceSolutionsAPAC solution allows financial Institution to issue and manage the Credit Card products to their end customers.
    tags: ["APAC", "FirstVision", "Credit"]
    bullets: ["Activate Card", "Block Card", "Lost Stolen Card Transfer", "CVV2 Validation" ]
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
      - relatedDoc: 
        title: Customer Management
        description: Allows management of a cardholder's demographic information like Name, Address, phone numbers.
        link: ./docs/Customer-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
      - relatedAPI: 
        title: Block-Unblock Card
        description: This service is used to update the block codes and the reason codes for the block codes for cards and accounts
        type: "post"        
        path: "/v1/cards/blockUnblock"
